### PR TITLE
Fixes #1230. Add test to make sure Asciidoctor version is returned wh…

### LINKED ISSUE #1230: Ensure AsciidoctorJ version is returned always in CLI
I see this null check https://github.com/asciidoctor/asciidoctorj/blob/6088e5b143646c8cd291542d9f95b55cbaaec0fb/asciidoctorj-cli/src/main/java/org/asciidoctor/cli/jruby/AsciidoctorInvoker.java#L93 and I wonder if we should remove it and ensure the version is always obtainable.

We could keep the check for resiliency, but log a message indicating something went wrong.

### PR DESCRIPTION
**Pull request by robertpanzer**
…en using --version

Thank you for opening a pull request and contributing to AsciidoctorJ!

Please take a bit of time giving some details about your pull request:

## Kind of change

- [x] Bug fix
- [ ] New non-breaking feature
- [ ] New breaking feature
- [ ] Documentation update
- [ ] Build improvement

## Description

What is the goal of this pull request?

This PR fixes #1230.
#1230 mentioned that we have a fallback when returning the version of the packaged Asciidoctor version.
This PR removes that fallback and would fail hard with a NullPointerException if the generated file containing the version numbers is not available.
Additionally a test makes sure that the generated file is available.

How does it achieve that?

Remove the fallback, and enhance the tests.

Are there any alternative ways to implement this?

We could search the class path for the asciidoctor gemspec and parse that, or maybe call some API exposed by JRuby to query the gems (or a Ruby-native API).

Are there any implications of this pull request? Anything a user must know?

No, everything should work as before.

## Issue

If this PR fixes an open issue, please add a line of the form:

Fixes #1230 

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by robertpanzer** [comment]
The upstream build obviously won't work with that.
I'll try to figure out a way to adapt the test accordingly.
Maybe I can make the version available to the test via a system property.

File: asciidoctorj-cli/src/test/java/org/asciidoctor/cli/WhenAsciidoctorIsCalledUsingCli.java [hunk 1]
```diff
@@ -274,6 +275,23 @@ void should_convert_to_subdirectories(@ClasspathResource("relative/sub/test.adoc
...
+    @Test
+    void should_print_version() throws IOException {
+        PrintStream previousSystemOut = System.out;
+        try (ByteArrayOutputStream out = new ByteArrayOutputStream();
+            PrintStream sysout = new PrintStream(out)){
+            System.setOut(sysout);
+            new AsciidoctorInvoker().invoke("--version");
+            String result = out.toString(StandardCharsets.UTF_8);
+            Assertions.assertThat(result)
+                    // Needs to be updated when version changes
```
Comment (abelsromero) [inline asciidoctorj-cli/src/test/java/org/asciidoctor/cli/WhenAsciidoctorIsCalledUsingCli.java:287]: Upstream tests fail on line 288, probabley related to the hardcoded assert. Maybe validate simply with a regex or read `asciidoctorj-version.properties` from classpath to assert it's the same?

PS1: Btw, since `createVersionFile` is run during `jar` I don't understand what file is being read during tests but tests work 🤔

**Review by abelsromero — CHANGES_REQUESTED** [review]

**Review by abelsromero — APPROVED** [review]
